#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

#
# Aliases
#

alias ack="ack-grep"
alias cp='nocorrect cp -iv'
alias l='ls -1AF'
alias l1='ls -1F'
alias ll='ls -lF'
alias mv='nocorrect mv -iv'
alias open='xdg-open'
alias rm='nocorrect rm -iv'
alias tvim="gvim --servername general --remote-tab"
alias vimcrypt="vim -u ~/.vimcryptrc -x"
alias wvim="gvim --servername general --remote-silent"

# fasd aliases
alias a='fasd -a'        # any
alias s='fasd -si'       # show / search / select
alias d='fasd -d'        # directory
alias f='fasd -f'        # file
alias sd='fasd -sid'     # interactive directory selection
alias sf='fasd -sif'     # interactive file selection
alias z='fasd_cd -d'     # cd, same functionality as j in autojump
alias zz='fasd_cd -d -i' # cd with interactive selection
alias v='f -e vim' # quick opening files with vim
alias m='f -e mplayer' # quick opening files with mplayer
alias o='a -e xdg-open' # quick opening files with xdg-open

#
# Dircolors
#

if [ -x /usr/bin/dircolors ]; then
    FILE=~/.zprezto/files/dircolors
    test -r $FILE && eval "$(dircolors $FILE)" || eval "$(dircolors -b)"
fi

#
# Options
#

# Let '#' be used for comments on the command line
setopt interactivecomments
# Don't overwrite files by piping with '>'.  To force overwrite, use '>!'
setopt noclobber
unsetopt COMPLETE_IN_WORD
unsetopt PATH_DIRS
unsetopt SHARE_HISTORY

#
# Key bindings
#

bindkey -M viins '^R' history-incremental-search-backward
bindkey -M vicmd '^R' history-incremental-search-backward

#
# Paths
#

if [[ "$OSTYPE" == darwin* ]]; then
    export PATH=/Applications/git-annex.app/Contents/MacOS:$PATH
fi

if [[ -e ~/.cabal/bin ]]; then export PATH=~/.cabal/bin:$PATH; fi
if [[ -e ~/admin/bin ]]; then export PATH=~/admin/bin:$PATH; fi
if [[ -e ~/repo/bin ]]; then export PATH=~/repo/bin:$PATH; fi
export PATH=$HOME/bin:$PATH

# 2014-01-28 ellis -- for panels in bspwm
export PANEL_FIFO="/tmp/panel-fifo"

#
# MacOS changes
#

if [[ "$OSTYPE" == darwin* ]]; then
    unalias open
    alias tvim="mvim --remote-tab"
    alias o='a -e open' # quick opening files with xdg-open
	alias vim="mvim -v"
	export LC_ALL=$LANG
	export LC_CTYPE=$LANG
	source /Users/ellisw/bin/bigsql/pg10/pg10.env
fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
